version: '3.3'

services:
  sigverify-database:
    image: postgres
    container_name: sigverify-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sigverifydb
    volumes:
      - data:/var/lib/postgresql/data
      # initalizes database with tables from database.sql
      - ../init-db:/docker-entrypoint-initdb.d
    networks:
    - sigverify-network

  sigverify-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sigverify-app
    working_dir: /usr/app
    restart: always
    ports:
      - 3001:3001
    # ! below volumes was causing Error: Cannot find module 'express' in my environment
    # volumes:
    #   - ../:/usr/app/
    networks:
    - sigverify-network

  sigverify-mailcatcher:
    container_name: sigverify-mailcatcher
    restart: on-failure
    image: stpaquet/alpinemailcatcher:latest
    ports:
    - "1080:1080"
    - "1025:1025"
    networks:
    - sigverify-network

volumes:
  data:
    driver: local

networks:
  sigverify-network:
    name: sigverify-network
    driver: bridge